import { Filme } from "../model/filme.js";

export const filmes: Filme[] = [
	{
		id: "FIL001",
		titulo: "Cidade de Deus",
		ano: 2002,
		genero: [
			{ id: "GEN001", nome: "Crime" },
			{ id: "GEN002", nome: "Drama" },
		],
		diretor: {
			id: "DIR001",
			nome: "Fernando Meirelles",
			nascimento: "1955-11-09",
			nacionalidade: "Brasileiro",
		},
		elenco: [
			{
				id: "ATR001",
				nome: "Alexandre Rodrigues",
				papel: "BuscapÃ©",
				nascimento: "1983-05-21",
				nacionalidade: "Brasileiro",
				biografia: "Alexandre Rodrigues é um ator brasileiro, conhecido por seu papel como Buscapé no filme 'Cidade de Deus'. Ele nasceu em 21 de maio de 1983, no Rio de Janeiro. Além de atuar, Alexandre também é músico e já participou de outros projetos cinematográficos e televisivos.",
			},
			{
				id: "ATR002",
				nome: "Leandro Firmino",
				papel: "ZÃ© Pequeno",
				nascimento: "1978-06-23",
				nacionalidade: "Brasileiro",
				biografia: "Leandro Firmino é um ator brasileiro, conhecido por seu papel como Zé Pequeno no filme 'Cidade de Deus'. Ele nasceu em 23 de junho de 1978, no Rio de Janeiro.",
			},
			{
				id: "ATR003",
				nome: "Phellipe Haagensen",
				papel: "BenÃ©",
				nascimento: "1984-06-26",
				nacionalidade: "Brasileiro",
				biografia: "Phellipe Haagensen é um ator brasileiro, conhecido por seu papel como Bené no filme 'Cidade de Deus'. Ele nasceu em 26 de junho de 1984, no Rio de Janeiro. Além de atuar, Phellipe também é músico e já participou de outros projetos cinematográficos e televisivos.",
			},
		],
		sinopse:
			"BuscapÃ© Ã© um jovem pobre, negro e muito sensÃ­vel, que cresce em um universo de muita violÃªncia. Ele vive na Cidade de Deus, favela carioca conhecida pela violÃªncia e pela criminalidade.",
	},
	{
		id: "FIL002",
		titulo: "Tropa de Elite",
		ano: 2007,
		genero: [
			{ id: "GEN001", nome: "Crime" },
			{ id: "GEN003", nome: "AÃ§Ã£o" },
		],
		diretor: {
			id: "DIR002",
			nome: "JosÃ© Padilha",
			nascimento: "1967-08-01",
			nacionalidade: "Brasileiro",
		},
		elenco: [
			{
				id: "ATR004",
				nome: "Wagner Moura",
				papel: "CapitÃ£o Nascimento",
				nascimento: "1976-06-27",
				nacionalidade: "Brasileiro",
				biografia: "Wagner Moura é um ator brasileiro, conhecido por seu papel como Capitão Nascimento no filme 'Tropa de Elite'. Ele nasceu em 27 de junho de 1976, no Rio de Janeiro.",
			},
			{
				id: "ATR005",
				nome: "AndrÃ© Ramiro",
				papel: "AndrÃ© Matias",
				nascimento: "1981-01-14",
				nacionalidade: "Brasileiro",
				biografia: "André Ramiro é um ator brasileiro, conhecido por seu papel como André Matias no filme 'Tropa de Elite'. Ele nasceu em 14 de janeiro de 1981, no Rio de Janeiro.",
			},
			{
				id: "ATR006",
				nome: "Caio Junqueira",
				papel: "Neto",
				nascimento: "1976-11-15",
				nacionalidade: "Brasileiro",
				biografia: "Caio Junqueira é um ator brasileiro, conhecido por seu papel como Neto no filme 'Tropa de Elite'. Ele nasceu em 15 de novembro de 1976, no Rio de Janeiro.",
			},
		],
		sinopse:
			"Em 1997, antes de visitar o Rio de Janeiro, o Papa JoÃ£o Paulo II solicita uma operaÃ§Ã£o para eliminar o trÃ¡fico de drogas nas favelas prÃ³ximas ao local onde pretende se hospedar.",
	},
	{
		id: "FIL003",
		titulo: "Central do Brasil",
		ano: 1998,
		genero: [{ id: "GEN002", nome: "Drama" }],
		diretor: {
			id: "DIR003",
			nome: "Walter Salles",
			nascimento: "1956-04-12",
			nacionalidade: "Brasileiro",
		},
		elenco: [
			{
				id: "ATR007",
				nome: "Fernanda Montenegro",
				papel: "Dora",
				nascimento: "1929-10-16",
				nacionalidade: "Brasileira",
				biografia: "Fernanda Montenegro é uma atriz brasileira, conhecida por seu papel como Dora no filme 'Central do Brasil'. Ela nasceu em 16 de outubro de 1929, em São Paulo.",
			},
			{
				id: "ATR008",
				nome: "VinÃ­cius de Oliveira",
				papel: "JosuÃ©",
				nascimento: "1985-07-18",
				nacionalidade: "Brasileiro",
				biografia: "Vinícius de Oliveira é um ator brasileiro, conhecido por seu papel como Josué no filme 'Central do Brasil'. Ele nasceu em 18 de julho de 1985, no Rio de Janeiro.",
			},
			{
				id: "ATR009",
				nome: "MarÃ­lia PÃªra",
				papel: "Irene",
				nascimento: "1943-01-22",
				nacionalidade: "Brasileira",
				biografia: "Marília Pêra foi uma atriz brasileira, conhecida por seu papel como Irene no filme 'Central do Brasil'. Ela nasceu em 22 de janeiro de 1943, no Rio de Janeiro, e faleceu em 5 de dezembro de 2015.",
			},
		],
		sinopse:
			"Dora escreve cartas para pessoas analfabetas na estaÃ§Ã£o Central do Brasil, no Rio de Janeiro. Quando uma de suas clientes morre em um acidente, ela decide ajudar o filho dela a encontrar o pai.",
	},
	{
		id: "FIL004",
		titulo: "O Auto da Compadecida",
		ano: 2000,
		genero: [
			{ id: "GEN004", nome: "ComÃ©dia" },
			{ id: "GEN002", nome: "Drama" },
		],
		diretor: {
			id: "DIR004",
			nome: "Guel Arraes",
			nascimento: "1953-12-07",
			nacionalidade: "Brasileiro",
		},
		elenco: [
			{
				id: "ATR010",
				nome: "Matheus Nachtergaele",
				papel: "JoÃ£o Grilo",
				nascimento: "1969-01-03",
				nacionalidade: "Brasileiro",
				biografia: "Matheus Nachtergaele é um ator e diretor brasileiro, conhecido por seu papel como JoÃ£o Grilo no filme 'O Auto da Compadecida'. Ele nasceu em 3 de janeiro de 1969, em São Paulo.",
			},
			{
				id: "ATR011",
				nome: "Selton Mello",
				papel: "ChicÃ³",
				nascimento: "1972-12-30",
				nacionalidade: "Brasileiro",
				biografia: "Selton Mello é um ator brasileiro, conhecido por seu papel como Chicó no filme 'O Auto da Compadecida'. Ele nasceu em 30 de dezembro de 1972, no Rio de Janeiro.",
			},
			{
				id: "ATR007",
				nome: "Fernanda Montenegro",
				papel: "Compadecida",
				nascimento: "1929-10-16",
				nacionalidade: "Brasileira",
				biografia: "Fernanda Montenegro é uma atriz brasileira, conhecida por seu papel como Compadecida no filme 'O Auto da Compadecida'. Ela nasceu em 16 de outubro de 1929, em São Paulo.",
			},
		],
		sinopse:
			"As aventuras de JoÃ£o Grilo e ChicÃ³, dois nordestinos pobres que tentam sobreviver aplicando golpes e se metendo em confusÃµes.",
	},
	{
		id: "FIL005",
		titulo: "Bacurau",
		ano: 2019,
		genero: [
			{ id: "GEN005", nome: "Suspense" },
			{ id: "GEN006", nome: "FicÃ§Ã£o CientÃ­fica" },
		],
		diretor: {
			id: "DIR005",
			nome: "Kleber MendonÃ§a Filho",
			nascimento: "1968-11-03",
			nacionalidade: "Brasileiro",
		},
		elenco: [
			{
				id: "ATR012",
				nome: "BÃ¡rbara Colen",
				papel: "Teresa",
				nascimento: "1986-12-14",
				nacionalidade: "Brasileira",
				biografia: "Bárbara Colen é uma atriz brasileira, conhecida por seu papel como Teresa no filme 'Bacurau'. Ela nasceu em 14 de dezembro de 1986, no Rio de Janeiro.",
			},
			{
				id: "ATR013",
				nome: "Thomas Aquino",
				papel: "Pacote",
				nascimento: "1986-06-26",
				nacionalidade: "Brasileiro",
				biografia: "Thomas Aquino é um ator brasileiro, conhecido por seu papel como Pacote no filme 'Bacurau'. Ele nasceu em 26 de junho de 1986, no Rio de Janeiro.",
			},
			{
				id: "ATR014",
				nome: "SÃ´nia Braga",
				papel: "Domingas",
				nascimento: "1950-06-08",
				nacionalidade: "Brasileira",
				biografia: "Sônia Braga é uma atriz brasileira, conhecida por seu papel como Domingas no filme 'Bacurau'. Ela nasceu em 8 de junho de 1950, no Rio de Janeiro.",
			},
		],
		sinopse:
			"Os moradores de Bacurau, um pequeno povoado do sertÃ£o brasileiro, descobrem que a comunidade nÃ£o consta mais em qualquer mapa. Aos poucos, percebem algo estranho na regiÃ£o: enquanto drones sobrevoam o cÃ©u, estrangeiros chegam Ã  cidade.",
	},
	{
		id: "FIL006",
		titulo: "Minha MÃ£e Ã© uma PeÃ§a",
		ano: 2013,
		genero: [{ id: "GEN004", nome: "ComÃ©dia" }],
		diretor: {
			id: "DIR006",
			nome: "AndrÃ© Pellenz",
			nascimento: "1971-09-30",
			nacionalidade: "Brasileiro",
		},
		elenco: [
			{
				id: "ATR015",
				nome: "Paulo Gustavo",
				papel: "Dona HermÃ­nia",
				nascimento: "1978-10-30",
				nacionalidade: "Brasileiro",
				biografia: "Paulo Gustavo é um ator e humorista brasileiro, conhecido por seu papel como Dona Hermínia no filme 'Minha Mãe é uma Peça'. Ele nasceu em 30 de outubro de 1978, em São Paulo.",
			},
			{
				id: "ATR016",
				nome: "Rodrigo Pandolfo",
				papel: "Juliano",
				nascimento: "1984-08-24",
				nacionalidade: "Brasileiro",
				biografia: "Rodrigo Pandolfo é um ator brasileiro, conhecido por seu papel como Juliano no filme 'Minha Mãe é uma Peça'. Ele nasceu em 24 de agosto de 1984, no Rio de Janeiro.",
			},
			{
				id: "ATR017",
				nome: "Mariana Xavier",
				papel: "Marcelina",
				nascimento: "1980-05-26",
				nacionalidade: "Brasileira",
				biografia: "Mariana Xavier é uma atriz brasileira, conhecida por seu papel como Marcelina no filme 'Minha Mãe é uma Peça'. Ela nasceu em 26 de maio de 1980, em São Paulo.",
			},
		],
		sinopse:
			"Dona HermÃ­nia Ã© uma mulher de meia-idade, divorciada do marido que a trocou por uma mulher mais jovem. Hiperativa e controladora, ela nÃ£o larga do pÃ© dos filhos Marcelina e Juliano.",
	},
	{
		id: "FIL007",
		titulo: "Que Horas Ela Volta?",
		ano: 2015,
		genero: [{ id: "GEN002", nome: "Drama" }],
		diretor: {
			id: "DIR007",
			nome: "Anna Muylaert",
			nascimento: "1964-04-21",
			nacionalidade: "Brasileira",
		},
		elenco: [
			{
				id: "ATR018",
				nome: "Regina CasÃ©",
				papel: "Val",
				nascimento: "1954-02-25",
				nacionalidade: "Brasileira",
				biografia: "Regina Casé é uma atriz brasileira, conhecida por seu papel como Val no filme 'Que Horas Ela Volta?'. Ela nasceu em 25 de fevereiro de 1954, no Rio de Janeiro.",
			},
			{
				id: "ATR019",
				nome: "Camila MÃ¡rdila",
				papel: "JÃ©ssica",
				nascimento: "1988-08-21",
				nacionalidade: "Brasileira",
				biografia: "Camila Márilda é uma atriz brasileira, conhecida por seu papel como Jéssica no filme 'Que Horas Ela Volta?'. Ela nasceu em 21 de agosto de 1988, em São Paulo.",
			},
			{
				id: "ATR020",
				nome: "Michel Joelsas",
				papel: "Fabinho",
				nascimento: "1995-03-18",
				nacionalidade: "Brasileiro",
				biografia: "Michel Joelsas é um ator brasileiro, conhecido por seu papel como Fabinho no filme 'Que Horas Ela Volta?'. Ele nasceu em 18 de março de 1995, em São Paulo.",
			},
		],
		sinopse:
			"A pernambucana Val se mudou para SÃ£o Paulo a fim de dar melhores condiÃ§Ãµes de vida Ã  filha JÃ©ssica. Treze anos depois, a jovem decide ir para SÃ£o Paulo prestar vestibular, o que abala a rotina da casa onde sua mÃ£e trabalha como empregada domÃ©stica.",
	},
	{
		id: "FIL008",
		titulo: "O Homem do Futuro",
		ano: 2011,
		genero: [
			{ id: "GEN006", nome: "FicÃ§Ã£o CientÃ­fica" },
			{ id: "GEN004", nome: "ComÃ©dia" },
		],
		diretor: {
			id: "DIR008",
			nome: "ClÃ¡udio Torres",
			nascimento: "1962-12-19",
			nacionalidade: "Brasileiro",
		},
		elenco: [
			{
				id: "ATR004",
				nome: "Wagner Moura",
				papel: "Zero",
				nascimento: "1976-06-27",
				nacionalidade: "Brasileiro",
				biografia: "Wagner Moura é um ator brasileiro, conhecido por seu papel como Zero no filme 'O Homem do Futuro'. Ele nasceu em 27 de junho de 1976, no Rio de Janeiro.",
			},
			{
				id: "ATR021",
				nome: "Alinne Moraes",
				papel: "Helena",
				nascimento: "1982-12-22",
				nacionalidade: "Brasileira",
				biografia: "Alinne Moraes é uma atriz brasileira, conhecida por seu papel como Helena no filme 'O Homem do Futuro'. Ela nasceu em 22 de dezembro de 1982, em São Paulo.",
			},
			{
				id: "ATR022",
				nome: "Maria LuÃ­sa MendonÃ§a",
				papel: "Sandra",
				nascimento: "1970-01-30",
				nacionalidade: "Brasileira",
				biografia: "Maria Luísa Mendonça é uma atriz brasileira, conhecida por seu papel como Sandra no filme 'O Homem do Futuro'. Ela nasceu em 30 de janeiro de 1970, em São Paulo.",
			},
		],
		sinopse:
			"Zero Ã© um cientista brilhante, mas infeliz, que acidentalmente descobre uma forma de viajar no tempo. Ele volta ao passado para tentar corrigir um erro que arruinou sua vida, mas acaba criando novas situaÃ§Ãµes inesperadas.",
	},
	{
		id: "FIL009",
		titulo: "Se Eu Fosse VocÃª",
		ano: 2006,
		genero: [
			{ id: "GEN004", nome: "ComÃ©dia" },
			{ id: "GEN002", nome: "Drama" },
		],
		diretor: {
			id: "DIR009",
			nome: "Daniel Filho",
			nascimento: "1937-09-30",
			nacionalidade: "Brasileiro",
		},
		elenco: [
			{
				id: "ATR023",
				nome: "Tony Ramos",
				papel: "ClÃ¡udio",
				nascimento: "1948-08-25",
				nacionalidade: "Brasileiro",
				biografia: "Tony Ramos é um ator brasileiro, conhecido por seu papel como Cláudio no filme 'Se Eu Fosse Você'. Ele nasceu em 25 de agosto de 1948, no Rio de Janeiro.",
			},
			{
				id: "ATR024",
				nome: "GlÃ³ria Pires",
				papel: "Helena",
				nascimento: "1963-08-23",
				nacionalidade: "Brasileira",
				biografia: "Glória Pires é uma atriz brasileira, conhecida por seu papel como Helena no filme 'Se Eu Fosse Você'. Ela nasceu em 23 de agosto de 1963, no Rio de Janeiro.",
			},
			{
				id: "ATR025",
				nome: "Thiago Lacerda",
				papel: "Marcos",
				nascimento: "1978-01-19",
				nacionalidade: "Brasileiro",
				biografia: "Thiago Lacerda é um ator brasileiro, conhecido por seu papel como Marcos no filme 'Se Eu Fosse Você'. Ele nasceu em 19 de janeiro de 1978, em São Paulo.",
			},
		],
		sinopse:
			"ClÃ¡udio e Helena formam um casal que vive em pÃ© de guerra. ApÃ³s uma briga, eles misteriosamente trocam de corpos e sÃ£o obrigados a viver a vida um do outro.",
	},
	{
		id: "FIL010",
		titulo: "Carandiru",
		ano: 2003,
		genero: [
			{ id: "GEN001", nome: "Crime" },
			{ id: "GEN002", nome: "Drama" },
		],
		diretor: {
			id: "DIR010",
			nome: "Hector Babenco",
			nascimento: "1946-02-07",
			nacionalidade: "Brasileiro",
		},
		elenco: [
			{
				id: "ATR026",
				nome: "Luiz Carlos Vasconcelos",
				papel: "Doutor Drauzio Varella",
				nascimento: "1954-06-25",
				nacionalidade: "Brasileiro",
				biografia: "Luiz Carlos Vasconcelos é um ator brasileiro, conhecido por seu papel como Doutor Drauzio Varella no filme 'Carandiru'. Ele nasceu em 25 de junho de 1954, no Rio de Janeiro.",
			},
			{
				id: "ATR027",
				nome: "Milton GonÃ§alves",
				papel: "Chico",
				nascimento: "1933-12-09",
				nacionalidade: "Brasileiro",
				biografia: "Milton Gonçalves é um ator brasileiro, conhecido por seu papel como Chico no filme 'Carandiru'. Ele nasceu em 9 de dezembro de 1933, no Rio de Janeiro.",
			},
			{
				id: "ATR028",
				nome: "Ivan de Almeida",
				papel: "Zico",
				nascimento: "1944-06-01",
				nacionalidade: "Brasileiro",
				biografia: "Ivan de Almeida é um ator brasileiro, conhecido por seu papel como Zico no filme 'Carandiru'. Ele nasceu em 1 de junho de 1944, no Rio de Janeiro.",
			},
		],
		sinopse:
			"Um mÃ©dico se oferece para realizar um trabalho de prevenÃ§Ã£o Ã  AIDS na Casa de DetenÃ§Ã£o de SÃ£o Paulo, o maior presÃ­dio da AmÃ©rica Latina. LÃ¡, ele conhece de perto a realidade dos detentos e testemunha a violenta rebeliÃ£o de 1992.",
	},
];
