@urlBase = http://localhost:4000

### 1. Cadastrar usuário
# @name postUsuario
POST {{urlBase}}/usuarios
Content-Type: application/json

{
  "nome": "Gerlucio",
  "email": "gerlucio@example.com",
  "senha": "123456"
}

### 2. Login com usuário cadastrado
# @name postLogin
POST {{urlBase}}/login
Content-Type: application/json

{
  "nome": "Zé Bode",
  "email": "zebode@example.com",
  "senha": "123456"
}

### 3. Guardar token retornado do login
@token = {{postLogin.response.body.token}}

### 4. Acessar rota protegida (filmes)
GET {{urlBase}}/filmes
Authorization: Bearer {{token}}

### rota protegida
GET {{urlBase}}/filmes
Authorization: Bearer {{token}}

###
POST http://localhost:4000/usuarios
Content-Type: application/json

{
  "nome": "Zé Butico",
  "email": "zebutico@example.com",
  "senha": "654321"
}

###
POST http://localhost:4000/usuarios
Content-Type: application/json

{
  "nome": "Mane Gambar",
  "email": "manegambar@example.com",
  "senha": "654321"
}

